#?????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/livegoods
spring.datasource.username=root
spring.datasource.password=root

#MyBatis??
mybatis.type-aliases-package=com.itbaizhan.pojo
mybatis.mapper-locations=classpath:mybatis/**/*.xml

spring.profiles.active=mysql