dubbo.application.name=${spring.application.name}-dubbo
dubbo.application.qos-enable=false
dubbo.application.serialize-check-status=WARN

dubbo.protocol.name=dubbo
dubbo.protocol.port=-1

# 注册中心
dubbo.registry.address=nacos://117.50.181.92:8848
dubbo.registry.username=nacos
dubbo.registry.password=nacos

# 元数据中心(对应 dubbo 分组里 :::provider:xxx 那条)
dubbo.metadata-report.address=nacos://117.50.181.92:8848
dubbo.metadata-report.username=nacos
dubbo.metadata-report.password=nacos

# 配置中心
dubbo.config-center.address=nacos://117.50.181.92:8848
dubbo.config-center.username=nacos
dubbo.config-center.password=nacos
