server.port=4006
spring.application.name=middleware-gateway
spring.profiles.active=discovery


spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.routes[0].id=banner
spring.cloud.gateway.routes[0].uri=lb://frontend-banner
spring.cloud.gateway.routes[0].predicates[0]=Path=/banner

spring.cloud.gateway.routes[1].id=hot
spring.cloud.gateway.routes[1].uri=lb://frontend-hot
spring.cloud.gateway.routes[1].predicates[0]=Path=/hotProduct
spring.cloud.gateway.routes[1].predicates[1]=Query=city
